name: Firehose

on:
  schedule:
    - cron: "30 */2 * * *"
  workflow_dispatch:

jobs:
  firehose:
    runs-on: ubuntu-latest
    env:
      DFUSE_TOKEN: ${{ secrets.DFUSE_TOKEN }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm start
    - run: git pull
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated data download
